version: '3.3'

services:

  sayna-web:
    build:
      context: ./sayna-web
      dockerfile: Dockerfile
    container_name: sayna-web
    hostname: sayna
    domainname: sayna.lo
    command: nginx -g "daemon off;"
    links:
      - sayna-php
    ports:
      - "7000:80"
    volumes:
      - ../:/var/www/html/
    networks:
      - sayna-network

  sayna-php:
    build:
      context: ./sayna-php
      dockerfile: Dockerfile
    container_name: sayna-php
    links:
      - sayna-db
      - sayna-cache
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html/
    command: php-fpm
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: sayna-db
      DB_DATABASE: sayna-database
      DB_USERNAME: sayna-user
      DB_PASSWORD: password
      MEMCACHED_HOST: sayna-cache
      CACHE_DRIVER: memcached
    networks:
      - sayna-network

  sayna-db:
    image: mysql:5.7
    container_name: sayna-db
    volumes:
      - ./sayna-db/data/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sayna-database
      MYSQL_USER: sayna-user
      MYSQL_PASSWORD: password
    networks:
      - sayna-network

  sayna-cache:
    image: memcached
    container_name: sayna-cache

networks:
  sayna-network:
    driver: bridge
